name: 'Custom GitHub Action'
description: 'A GitHub Action that takes an input and returns the square of the number'
inputs:
  num:
    description: 'Enter a number'
    required: false
    default: "1"
  first_num:
    description: 'Enter first number'
    required: false
    default: "1"
  second_num:
    description: 'Enter second number'
    required: false
    default: "1"
  func_needed:
    description: 'Enter function'
    required: false
    default: "add"
outputs:
  num-squared:
    description: 'Square of the input'
    value: 1
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Pass inputs to shell
      run: |
        echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
        echo "FIRST_NUM=${{ inputs.first_num }}"
        echo "SECOND_NUM=${{ inputs.second_num }}"
        echo "FUNC_NEEDED=${{ inputs.func_needed }}"
      shell: bash
    - name: Fetch the number's square
      id: get-square
      run: python ./.github/python-scripts/get_num_squared.py
      shell: bash
    - name: Calculate
      id: calculate
      run: python ./.github/python-scripts/calculate.py
      shell: bash