name: Deploy workflow
on: [workflow _dispatch, push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy job
        run: echo "Deploying"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch number squared
        id: get-square
        uses: ./.github/python-scripts
        with:
          num: "11"
      - name: Calculate
        id: calculate
        uses: ./.github/python-scripts
        with:
          first_num: "11"
          second_num: "200"
          func_needed: "multiply"