name: Deploy workflow
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy job
        run: echo "Deploying"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch number squared
        id: get-square
        uses: ./.github/python-scripts
        with:
          num: 11